name=incipe
version=v0.0.1
author=Incipe
maintainer=Incipe
sentence=Incipe mainboard support
paragraph=Internal library for the IA Kit mainboard.
category=Signal Input/Output
url=https://example.com
architectures=*